[package]
name = "easy-set"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.8.19"
serde =  { version = "1.0.217", features = ["derive"] }
gethostname = "0.5.0"
prettytable-rs = "0.10.0"
winreg = "0.52.0"